$(function(){     
    $(".left").click(function(){
        $("p").css({"text-align":"left"});
    });
    $(".center").click(function(){
        $("p").css({"text-align":"center"});
    });
    $(".right").click(function(){
        $("p").css({"text-align":"right"});
    });
    $(".normal").click(function(){
        $("p").css({"font-size":"medium"});
    });
    $(".10px").click(function(){
        $("p").css({"font-size":"10px"});
    });
    $(".20px").click(function(){
        $("p").css({"font-size":"20px"});
    });
    $(".50px").click(function(){
        $("p").css({"font-size":"50px"});
    });
    $(".80px").click(function(){
        $("p").css({"font-size":"80px"});
    });
    $(".100px").click(function(){
        $("p").css({"font-size":"100px"});
    });
    $(".white").click(function(){
        $("p").css({"color":"white"});
    });
    $(".black").click(function(){
        $("p").css({"color":"black"});
    });
    $(".red").click(function(){
        $("p").css({"color":"red"});
    });
    $(".green").click(function(){
        $("p").css({"color":"green"});
    });
    $(".blue").click(function(){
        $("p").css({"color":"blue"});
    });
    $(".yellow").click(function(){
        $("p").css({"color":"yellow"});
    });
    $(".orange").click(function(){
        $("p").css({"color":"orange"});
    });
    $(".violet").click(function(){
        $("p").css({"color":"violet"});
    });
    $(".indigo").click(function(){
        $("p").css({"color":"indigo"});
    });
    $(".pink").click(function(){
        $("p").css({"color":"pink"});
    });
    $(".maroon").click(function(){
        $("p").css({"color":"maroon"});
    });
    $(".brown").click(function(){
        $("p").css({"color":"brown"});
    });
    $(".grey").click(function(){
        $("p").css({"color":"grey"});
    });
    $(".bgwhite").click(function(){
        $("p").css({"background":"white"});
        });
    $(".bgblack").click(function(){
        $("p").css({"background":"black"});
    });
    $(".bgred").click(function(){
        $("p").css({"background":"red"});
    });
    $(".bggreen").click(function(){
        $("p").css({"background":"green"});
    });
    $(".bgblue").click(function(){
        $("p").css({"background":"blue"});
    });
    $(".bgyellow").click(function(){
        $("p").css({"background":"yellow"});
    });
    $(".bgorange").click(function(){
        $("p").css({"background":"orange"});
    });
    $(".bgviolet").click(function(){
        $("p").css({"background":"violet"});
    });
    $(".bgindigo").click(function(){
        $("p").css({"background":"indigo"});
    });
    $(".bgpink").click(function(){
        $("p").css({"background":"pink"});
    });
    $(".bgmaroon").click(function(){
        $("p").css({"background":"maroon"});
    });
    $(".bgbrown").click(function(){
        $("p").css({"background":"brown"});
    });
    $(".bggrey").click(function(){
        $("p").css({"background":"grey"});
    });
    $(".bgrainbow").click(function(){
        $("p").css({"background":"linear-gradient(red,orange,yellow,green,blue,indigo,violet)"});
    });
    $(".none").click(function(){
       $("p").css({"text-decoration":"none"});
    });
    $(".underline").click(function(){
       $("p").css({"text-decoration":"underline"});
    });    
    $(".line-through").click(function(){
        $("p").css({"text-decoration":"line-through"});
    }); 
    $(".overline").click(function(){
        $("p").css({"text-decoration":"overline"});
    }); 
    $(".fnormal").click(function(){
       $("p").css({"font-family":""});
    });
    $(".sans-serif").click(function(){
       $("p").css({"font-family":"sans-serif"});
    });
    $(".serif").click(function(){
       $("p").css({"font-family":"serif"});
    });
    $(".monospace").click(function(){
       $("p").css({"font-family":"monospace"});
    });
    $(".cursive").click(function(){
       $("p").css({"font-family":"cursive"});
    });
    $(".fantasy").click(function(){
       $("p").css({"font-family":"fantasy"});
    });
    $(".normal").click(function(){
        $("p").css({"font-style":"normal"});
    });
    $(".italic").click(function(){
        $("p").css({"font-style":"italic"});
    });
    $(".oblique").click(function(){
        $("p").css({"font-style":"oblique"});
    });
    $(".initial").click(function(){
       $("p").css({"font-style":"initial"});
    });        
    $(".none").click(function(){
       $("p").css({"text-shadow":"0px 0px 0px "});
    });
    $(".rb").click(function(){
       $("p").css({"text-shadow":"3px 3px 5px black"});
    }); 
    $(".lb").click(function(){
       $("p").css({"text-shadow":"-3px 3px 5px black"});
    });
    $(".rt").click(function(){
       $("p").css({"text-shadow":"3px -3px 5px black"});
    });
    $(".lt").click(function(){
       $("p").css({"text-shadow":"-3px -3px 5px black"});
    });   
});